site_name: Hello Trading Docs

# Theme configuration (changed from readthedocs to material for better tab support)
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: blue

# Navigation
nav:
  - Home: index.md
  - Docker Guide: docker.md  # Example additional page

# Plugins
plugins:
  - mermaid2

# Markdown extensions
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition