site_name: Hello Trading Docs

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs
    - content.tabs  # Changed from content.code.annotate
    - content.code.copy  # Added for copy-to-clipboard buttons
  palette:
    - scheme: default
      primary: indigo
      accent: blue

# Navigation
nav:
  - Home: index.md
  - Docker Guide: docker.md

# Plugins
plugins:
  - mermaid2:
      version: "10.6.1"
      arguments:  # Add Mermaid initialization
        theme: dark
        securityLevel: loose

# Markdown extensions
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true