name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Install static site generator (e.g., MkDocs or Sphinx)
          pip install mkdocs

      - name: Build static site
        run: |
          # Generate HTML files (replace with your build command)
          mkdocs build --site-dir site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site/"  # Upload the built static files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
